language: elixir
elixir:
  - 1.13
otp_release:
  - 24.3
notifications:
  recipients:
    - travis@jeffweiss.org
    - matt@mattrobinson.net
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - mix do deps.get, deps.compile, compile
  - mix test
  - travis_wait 30 mix dialyzer --halt-exit-status --format term;
