language: elixir
elixir:
  - 1.6
  - 1.7
otp_release:
  - 20.3
  - 21.0
notifications:
  recipients:
    - travis@jeffweiss.org
    - matt@mattrobinson.net
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - mix do deps.get, deps.compile, compile
  - mix test
  - if [[ `elixir -v` = *"1.7"* ]]; then
      travis_wait 30 mix dialyzer --halt-exit-status --format term;
    fi
